import {
  Code,
  ExternalLink,
  FileText,
  Search,
  Shield,
  Activity,
  MessageSquare,
  Heart,
  Terminal,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  Plug,
  Bot,
  Download,
  Image as ImageIcon,
  Server,
  Bookmark,
} from "lucide-react";
import { useState } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
// Task #679 — Browser bookmarklet install button. The href is generated by
// `sdks/bookmarklet/generate.mjs` (the only blessed source of truth) and
// imported as a raw string so the rendered drag-target and the checked-in
// `vulnrap.bookmarklet.url` artifact can never drift.
import bookmarkletHrefRaw from "../../../../sdks/bookmarklet/vulnrap.bookmarklet.url?raw";

const BOOKMARKLET_HREF = bookmarkletHrefRaw.trim();

function CopyBlock({ code, language }: { code: string; language: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative group">
      <pre className="glass-card rounded-xl p-4 text-sm font-mono whitespace-pre-wrap overflow-x-auto leading-relaxed text-muted-foreground">
        <code>{code}</code>
      </pre>
      <button
        onClick={handleCopy}
        className="absolute top-3 right-3 p-1.5 rounded-md bg-muted/50 hover:bg-muted text-muted-foreground hover:text-primary transition-all sm:opacity-0 sm:group-hover:opacity-100"
      >
        {copied ? (
          <Check className="w-3.5 h-3.5" />
        ) : (
          <Copy className="w-3.5 h-3.5" />
        )}
      </button>
    </div>
  );
}

const endpoints = [
  {
    method: "POST",
    path: "/api/reports",
    title: "Submit a Report",
    description:
      "Upload a vulnerability report for full analysis — multi-engine consensus scoring, similarity matching, auto-redaction, and section-level hashing.",
    badge: "Write",
    badgeColor: "border-green-500 text-green-500",
    example: `# Upload a file
curl -X POST https://vulnrap.com/api/reports \\
  -F "file=@my-report.txt" \\
  -F "contentMode=full"

# Or submit via URL (GitHub, Gist, GitLab, Pastebin, etc.)
curl -X POST https://vulnrap.com/api/reports \\
  -F "reportUrl=https://github.com/user/repo/blob/main/report.md" \\
  -F "contentMode=full"`,
    responseHint:
      "Returns report ID, delete token, vulnrap composite (score + label + per-engine breakdown for AI Authorship / Technical Substance / CWE Coherence), legacy slopScore (mapped from composite), llmFeedback, heuristic feedback, similarity matches, redaction summary, and a correlation id for diagnostics lookup",
  },
  {
    method: "DELETE",
    path: "/api/reports/:id",
    title: "Delete a Report",
    description:
      "Permanently delete a report and all associated data (hashes, similarity records, redacted text). Requires the delete token returned at submission time.",
    badge: "Write",
    badgeColor: "border-red-500 text-red-500",
    example: `curl -X DELETE https://vulnrap.com/api/reports/42 \\
  -H "Content-Type: application/json" \\
  -d '{"deleteToken": "your-token-here"}'`,
    responseHint:
      "Returns confirmation message. Deletion is permanent and irreversible.",
  },
  {
    method: "POST",
    path: "/api/reports/check",
    title: "Check a Report (Read-Only)",
    description:
      "Run the full analysis pipeline without storing anything. Ideal for PSIRT teams validating incoming reports.",
    badge: "Read-Only",
    badgeColor: "border-cyan-500 text-cyan-500",
    example: `# Paste text directly
curl -X POST https://vulnrap.com/api/reports/check \\
  -F "rawText=Your report text here..."

# Or check via URL
curl -X POST https://vulnrap.com/api/reports/check \\
  -F "reportUrl=https://gist.github.com/user/abc123"`,
    responseHint:
      "Returns vulnrap composite (score + label + per-engine breakdown), legacy slopScore (mapped from composite), llmFeedback, similarity matches, section hashes — nothing saved",
  },
  {
    method: "GET",
    path: "/api/reports/:id",
    title: "Get Report Results",
    description:
      "Retrieve the full analysis results for a previously submitted report.",
    badge: "Read",
    badgeColor: "border-blue-500 text-blue-500",
    example: `curl https://vulnrap.com/api/reports/42`,
    responseHint:
      "Returns full analysis: redacted text, slop score, matches, sections",
  },
  {
    method: "GET",
    path: "/api/reports/:id/diagnostics",
    title: "Pipeline Diagnostics",
    description:
      'Returns the full pipeline trace for a report — composite breakdown, per-engine scores and verdicts, applied overrides, perplexity signals, input signals summary, per-stage timings (correlation id), and the legacy slop-score mapping. Powers the "Why this score?" panel on the report detail page.',
    badge: "Read",
    badgeColor: "border-blue-500 text-blue-500",
    example: `curl https://vulnrap.com/api/reports/42/diagnostics`,
    responseHint:
      "Returns composite, engines[], perplexity, overridesApplied, warnings, trace { correlationId, stages[], signalsSummary }, legacyMapping { slopScore, displayMode, note }, featureFlags",
  },
  {
    method: "GET",
    path: "/api/reports/:id/verify",
    title: "Verify a Report",
    description:
      "Lightweight verification endpoint — returns just the badge data (slop score, match counts, content hash) for embedding or sharing.",
    badge: "Read",
    badgeColor: "border-blue-500 text-blue-500",
    example: `curl https://vulnrap.com/api/reports/42/verify`,
    responseHint: "Returns slop score, match counts, content hash, verify URL",
  },
  {
    method: "GET",
    path: "/api/reports/lookup/:hash",
    title: "Lookup by Hash",
    description:
      "Find a report by its SHA-256 content hash. Useful for deduplication workflows.",
    badge: "Read",
    badgeColor: "border-blue-500 text-blue-500",
    example: `curl https://vulnrap.com/api/reports/lookup/abc123...`,
    responseHint: "Returns the report if found, 404 otherwise",
  },
  {
    method: "GET",
    path: "/api/stats",
    title: "Platform Statistics",
    description:
      "Aggregate stats: total reports, duplicate count, average slop score, today's submissions.",
    badge: "Read",
    badgeColor: "border-blue-500 text-blue-500",
    example: `curl https://vulnrap.com/api/stats`,
    responseHint:
      "Returns totalReports, duplicatesDetected, avgSlopScore, reportsByMode",
  },
  {
    method: "POST",
    path: "/api/feedback",
    title: "Submit Feedback",
    description:
      "Submit user feedback about the platform — rating, helpfulness, and optional comments.",
    badge: "Write",
    badgeColor: "border-green-500 text-green-500",
    example: `curl -X POST https://vulnrap.com/api/feedback \\
  -H "Content-Type: application/json" \\
  -d '{"rating": 5, "helpful": true, "comment": "Great tool!"}'`,
    responseHint: "Returns confirmation of feedback submission",
  },
];

export default function ApiDocs() {
  const apiDocsUrl = "/api/docs/";
  const [swaggerOpen, setSwaggerOpen] = useState(false);

  return (
    <div className="max-w-4xl mx-auto space-y-10">
      <div className="border-b border-border pb-6">
        <h1 className="text-3xl font-bold uppercase tracking-tight flex items-center gap-3">
          <Code className="w-8 h-8 text-primary" />
          API Documentation
        </h1>
        <p className="text-muted-foreground mt-2 max-w-3xl leading-relaxed">
          Integrate VulnRap directly into your workflow. All endpoints are free,
          anonymous, and require no authentication. Use them with your own
          tools, CI/CD pipelines, or triage systems.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card className="glass-card-accent rounded-xl">
          <CardContent className="p-6 flex flex-col items-center text-center gap-4">
            <div className="p-3 rounded-lg icon-glow-cyan">
              <Terminal className="w-6 h-6 text-cyan-400" />
            </div>
            <div>
              <h3 className="font-bold text-sm mb-1">
                Interactive API Explorer
              </h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Full Swagger UI with try-it-out functionality. Test every
                endpoint directly in your browser.
              </p>
            </div>
            <Button
              className="glow-button gap-2"
              onClick={() => setSwaggerOpen((v) => !v)}
            >
              {swaggerOpen ? "Hide" : "Open"} Swagger UI{" "}
              {swaggerOpen ? (
                <ChevronUp className="w-3.5 h-3.5" />
              ) : (
                <ChevronDown className="w-3.5 h-3.5" />
              )}
            </Button>
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardContent className="p-6 flex flex-col items-center text-center gap-4">
            <div className="p-3 rounded-lg icon-glow-green">
              <Shield className="w-6 h-6 text-green-400" />
            </div>
            <div>
              <h3 className="font-bold text-sm mb-1">No Auth Required</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                All endpoints are open and anonymous. No API keys, no accounts,
                no rate limits beyond basic abuse protection (100 req / 15 min).
              </p>
            </div>
            <Badge
              variant="outline"
              className="border-green-500/30 text-green-400"
            >
              Free & Open
            </Badge>
          </CardContent>
        </Card>
      </div>

      {swaggerOpen && (
        <Card className="glass-card rounded-xl overflow-hidden">
          <CardContent className="p-0">
            <iframe
              src={apiDocsUrl}
              title="Swagger UI"
              className="w-full border-0 rounded-xl bg-white"
              style={{ height: "80vh", minHeight: "500px" }}
            />
          </CardContent>
        </Card>
      )}

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          Quick Start
        </h2>
        <p className="text-sm text-muted-foreground">
          Submit a report and get results in two requests:
        </p>
        <CopyBlock
          language="bash"
          code={`# 1. Submit a report for analysis
curl -X POST https://vulnrap.com/api/reports \\
  -F "file=@vulnerability-report.txt" \\
  -F "contentMode=full"

# Response: { "id": 42, "slopScore": 12, ... }

# 2. Retrieve the full results
curl https://vulnrap.com/api/reports/42

# Or check a report without storing it (read-only)
curl -X POST https://vulnrap.com/api/reports/check \\
  -F "rawText=Your report content here..."`}
        />
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Search className="w-5 h-5 text-primary" />
          Endpoints
        </h2>

        <div className="space-y-3">
          {endpoints.map((ep, i) => (
            <Card key={i} className="glass-card rounded-xl">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Badge
                      variant="outline"
                      className={
                        ep.badgeColor + " text-[10px] font-mono uppercase"
                      }
                    >
                      {ep.method}
                    </Badge>
                    <code className="text-primary font-mono text-xs">
                      {ep.path}
                    </code>
                  </CardTitle>
                  <Badge variant="secondary" className="text-[10px]">
                    {ep.badge}
                  </Badge>
                </div>
                <CardDescription className="mt-1">
                  {ep.description}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                <CopyBlock language="bash" code={ep.example} />
                <p className="text-[11px] text-muted-foreground/60 italic">
                  {ep.responseHint}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <ImageIcon className="w-5 h-5 text-primary" />
          Embed Badge
        </h2>
        <p className="text-sm text-muted-foreground">
          Drop a Shields.io-style score badge next to a report ID in your triage
          tracker, README, or HackerOne / Bugcrowd comment. The endpoint always
          returns 200 OK with a well-formed SVG — unknown or hidden ids render a
          graceful "unknown" pill, so a broken image never appears on your page.
          ETag + cache headers let embedders re-render the page cheaply.
        </p>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-blue-500 text-blue-500 text-[10px] font-mono uppercase"
              >
                GET
              </Badge>
              <code className="text-primary font-mono text-xs">
                /api/embed/badge.svg?id=VR-XXXX
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Live preview (uses report{" "}
              <code className="font-mono text-xs text-foreground">VR-002A</code>{" "}
              if present, otherwise the "unknown" badge):
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex items-center gap-3 flex-wrap">
              <img
                src="/api/embed/badge.svg?id=VR-002A"
                alt="VulnRap badge for VR-002A"
                className="h-5"
                data-testid="embed-badge-preview"
              />
              <span className="text-[11px] text-muted-foreground/60 italic">
                Replace <code className="font-mono">VR-002A</code> with your own
                report id.
              </span>
            </div>

            <div>
              <p className="text-[11px] text-muted-foreground/60 mb-1 uppercase tracking-wide">
                HTML
              </p>
              <CopyBlock
                language="html"
                code={`<img src="https://vulnrap.com/api/embed/badge.svg?id=VR-002A" alt="VulnRap score" />`}
              />
            </div>

            <div>
              <p className="text-[11px] text-muted-foreground/60 mb-1 uppercase tracking-wide">
                Markdown
              </p>
              <CopyBlock
                language="markdown"
                code={`![VulnRap score](https://vulnrap.com/api/embed/badge.svg?id=VR-002A)`}
              />
            </div>

            <div>
              <p className="text-[11px] text-muted-foreground/60 mb-1 uppercase tracking-wide">
                Linked Markdown (clicks through to the verify page)
              </p>
              <CopyBlock
                language="markdown"
                code={`[![VulnRap score](https://vulnrap.com/api/embed/badge.svg?id=VR-002A)](https://vulnrap.com/verify/42)`}
              />
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Code className="w-5 h-5 text-primary" />
          Official SDKs
        </h2>
        <p className="text-sm text-muted-foreground">
          Hand-written, idiomatic clients that wrap the four most common
          endpoints. No code generation, no extra dependencies.
        </p>

        <Card className="glass-card rounded-xl" data-testid="card-sdk-python">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-yellow-500 text-yellow-500 text-[10px] font-mono uppercase"
              >
                Python
              </Badge>
              <code className="text-primary font-mono text-xs">
                pip install vulnrap
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Idiomatic Python client for security teams scripting PSIRT
              workflows, CI gates, and triage bots. Methods:{" "}
              <code className="font-mono text-xs text-foreground">
                score_report
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                lookup_report
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                query_stats
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                test_yourself
              </code>
              . Fully type-hinted (
              <code className="font-mono text-xs text-foreground">
                py.typed
              </code>
              ), one runtime dep (
              <code className="font-mono text-xs text-foreground">httpx</code>),
              typed errors via{" "}
              <code className="font-mono text-xs text-foreground">
                vulnrap.APIError
              </code>
              .
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <CopyBlock
              language="python"
              code={`pip install vulnrap

from vulnrap import Client

with Client() as c:
    res = c.test_yourself(raw_text="Found a path traversal in /api/files...")
    print(f"slop={res.slop_score}/{res.slop_tier} confidence={res.confidence:.2f}")`}
            />
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/sdks/python/vulnrap/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-python-sdk-readme"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the Python SDK docs
              <ExternalLink className="w-3 h-3" />
            </a>
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl" data-testid="card-sdk-go">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-cyan-500 text-cyan-500 text-[10px] font-mono uppercase"
              >
                Go
              </Badge>
              <code className="text-primary font-mono text-xs">
                github.com/vulnrap/vulnrap/sdks/go/vulnrap
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Pure standard-library Go client for cloud-native security tooling
              and CI gates. Methods:{" "}
              <code className="font-mono text-xs text-foreground">
                ScoreReport
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                LookupReport
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                QueryStats
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                TestYourself
              </code>
              . Idiomatic{" "}
              <code className="font-mono text-xs text-foreground">
                context.Context
              </code>
              -first API, typed errors via{" "}
              <code className="font-mono text-xs text-foreground">
                *vulnrap.APIError
              </code>
              , no panics.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <CopyBlock
              language="go"
              code={`go get github.com/vulnrap/vulnrap/sdks/go/vulnrap

import (
    "context"
    "log"

    "github.com/vulnrap/vulnrap/sdks/go/vulnrap"
)

func main() {
    c := vulnrap.NewClient()
    res, err := c.TestYourself(context.Background(), &vulnrap.TestYourselfInput{
        RawText: "Found a path traversal in /api/files...",
    })
    if err != nil { log.Fatal(err) }
    log.Printf("slop=%d/%s confidence=%.2f", res.SlopScore, res.SlopTier, res.Confidence)
}`}
            />
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/sdks/go/vulnrap/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-go-sdk-readme"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the Go SDK docs
              <ExternalLink className="w-3 h-3" />
            </a>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Download className="w-5 h-5 text-primary" />
          Postman Collection
        </h2>
        <p className="text-sm text-muted-foreground">
          Prefer clicking through endpoints to writing curl? Import the
          auto-generated Postman v2.1 collection. Insomnia, Bruno, and
          Hoppscotch accept the same file.
        </p>

        <Card className="glass-card rounded-xl" data-testid="card-postman">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-orange-500 text-orange-500 text-[10px] font-mono uppercase"
              >
                Postman
              </Badge>
              <code className="text-primary font-mono text-xs">
                vulnrap.postman_collection.json
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Every public endpoint, folded into folders by tag, with a single{" "}
              <code className="font-mono text-xs text-foreground">
                {"{{baseUrl}}"}
              </code>{" "}
              variable defaulting to{" "}
              <code className="font-mono text-xs text-foreground">
                https://vulnrap.com/api
              </code>
              . Regenerated from the OpenAPI spec — never hand-edited.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex flex-wrap gap-2">
              <Button
                asChild
                className="glow-button gap-2"
                data-testid="button-download-postman"
              >
                <a
                  href="/vulnrap.postman_collection.json"
                  download="vulnrap.postman_collection.json"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download Postman collection
                </a>
              </Button>
              <Button
                asChild
                variant="outline"
                className="gap-2"
                data-testid="link-postman-readme"
              >
                <a
                  href="https://github.com/vulnrap/vulnrap/blob/main/sdks/postman/README.md"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <FileText className="w-3.5 h-3.5" />
                  Import instructions
                  <ExternalLink className="w-3 h-3" />
                </a>
              </Button>
            </div>
            <p className="text-[11px] text-muted-foreground/60 italic">
              Repo path:{" "}
              <code className="font-mono">
                sdks/postman/vulnrap.postman_collection.json
              </code>{" "}
              — regenerate with{" "}
              <code className="font-mono">
                pnpm --filter @workspace/scripts run generate:postman
              </code>
              .
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Bookmark className="w-5 h-5 text-primary" />
          Browser Bookmarklet
        </h2>
        <p className="text-sm text-muted-foreground">
          Drag the button below onto your bookmarks bar. Click it on any page (a
          HackerOne report, a Bugcrowd submission, an email, …) to open{" "}
          <code className="font-mono text-xs text-foreground">/check</code> with
          the currently selected text pre-filled. No extension to install, no
          permissions to grant.
        </p>

        <Card className="glass-card rounded-xl" data-testid="card-bookmarklet">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-purple-500 text-purple-500 text-[10px] font-mono uppercase"
              >
                Bookmarklet
              </Badge>
              <code className="text-primary font-mono text-xs">
                javascript:(...)
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              One-line IIFE that grabs{" "}
              <code className="font-mono text-xs text-foreground">
                window.getSelection()
              </code>{" "}
              and opens{" "}
              <code className="font-mono text-xs text-foreground">
                vulnrap.com/check?text=&lt;encoded&gt;
              </code>{" "}
              in a new tab. Selections longer than 50,000 chars are truncated to
              stay under URL length limits. Does not auto-submit — you always
              click <strong>Check</strong> yourself.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex flex-wrap items-center gap-3">
              <a
                href={BOOKMARKLET_HREF}
                onClick={(e) => e.preventDefault()}
                draggable
                className="inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-bold bg-primary text-primary-foreground glow-button cursor-grab active:cursor-grabbing select-none no-underline"
                data-testid="button-install-bookmarklet"
                title="Drag this onto your bookmarks bar"
              >
                <Bookmark className="w-3.5 h-3.5" />
                Check selection on VulnRap
              </a>
              <span className="text-xs text-muted-foreground">
                ← Drag onto your bookmarks bar
              </span>
            </div>
            <div className="rounded-lg bg-muted/30 px-4 py-3 text-xs text-muted-foreground leading-relaxed space-y-1.5">
              <p className="font-medium text-foreground/80">Manual install</p>
              <p>
                If your browser blocks dragging, create a new bookmark and paste
                the contents of{" "}
                <code className="font-mono">
                  sdks/bookmarklet/vulnrap.bookmarklet.url
                </code>{" "}
                as the URL.
              </p>
            </div>
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/sdks/bookmarklet/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-bookmarklet-readme"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the bookmarklet docs
              <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-[11px] text-muted-foreground/60 italic">
              Repo path: <code className="font-mono">sdks/bookmarklet/</code> —
              regenerate with{" "}
              <code className="font-mono">
                pnpm --filter @workspace/scripts run generate:bookmarklet
              </code>
              .
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Plug className="w-5 h-5 text-primary" />
          GitHub Action
        </h2>
        <p className="text-sm text-muted-foreground">
          Drop-in composite action that scores incoming security advisory PRs
          (or VDP issue bodies) against VulnRap and exposes the slop score,
          tier, and triage verdict as step outputs you can gate merges on or
          post back as PR comments. Pure{" "}
          <code className="font-mono text-xs text-foreground">bash</code> +{" "}
          <code className="font-mono text-xs text-foreground">curl</code> +{" "}
          <code className="font-mono text-xs text-foreground">jq</code>, no{" "}
          <code className="font-mono text-xs text-foreground">
            node_modules
          </code>
          .
        </p>

        <Card
          className="glass-card rounded-xl"
          data-testid="card-github-action"
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-primary/40 text-primary text-[10px] font-mono uppercase"
              >
                GitHub Action
              </Badge>
              <code className="text-primary font-mono text-xs">
                vulnrap/vulnrap/sdks/github-action
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Inputs:{" "}
              <code className="font-mono text-xs text-foreground">
                report-text
              </code>{" "}
              or{" "}
              <code className="font-mono text-xs text-foreground">
                report-file
              </code>
              , optional{" "}
              <code className="font-mono text-xs text-foreground">
                fail-threshold
              </code>{" "}
              (default 70). Outputs:{" "}
              <code className="font-mono text-xs text-foreground">
                slop-score
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                slop-tier
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">verdict</code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                quality-score
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                confidence
              </code>
              ,{" "}
              <code className="font-mono text-xs text-foreground">
                similarity-match-count
              </code>
              .
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <CopyBlock
              language="yaml"
              code={`name: VulnRap triage

on:
  pull_request:
    paths:
      - "advisories/**.md"

jobs:
  score:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so the diff against the base branch works

      - name: Pick the changed advisory
        id: pick
        run: |
          file=$(git diff --name-only origin/\${{ github.base_ref }}... \\
                  | grep -E '^advisories/.*\\.md$' | head -n1)
          echo "file=\${file}" >> "$GITHUB_OUTPUT"

      - name: Score with VulnRap
        id: vulnrap
        if: steps.pick.outputs.file != ''
        uses: vulnrap/vulnrap/sdks/github-action@main
        with:
          report-file: \${{ steps.pick.outputs.file }}
          fail-threshold: 80   # block the PR if it scores 80+

      - name: Comment on the PR
        if: steps.pick.outputs.file != ''
        uses: actions/github-script@v7
        with:
          script: |
            const score   = \`\${{ steps.vulnrap.outputs.slop-score }}\`;
            const tier    = \`\${{ steps.vulnrap.outputs.slop-tier }}\`;
            const verdict = \`\${{ steps.vulnrap.outputs.verdict }}\`;
            const dupes   = \`\${{ steps.vulnrap.outputs.similarity-match-count }}\`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`### VulnRap analysis\\n\\n- **Slop score:** \${score}/100 (\${tier})\\n- **Verdict:** \\\`\${verdict}\\\`\\n- **Similar reports:** \${dupes}\`,
            });`}
            />
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/sdks/github-action/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-github-action-readme"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the GitHub Action docs
              <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-[11px] text-muted-foreground/60 italic mt-2">
              Repo path: <code className="font-mono">sdks/github-action/</code>{" "}
              — not published to the Marketplace; reference by repo path or
              vendor it.
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Plug className="w-5 h-5 text-primary" />
          Integration Recipes
        </h2>
        <p className="text-sm text-muted-foreground">
          End-to-end walkthroughs for wiring VulnRap into specific triage
          platforms. Pure docs — copy the scripts, adapt to your environment.
        </p>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-primary/40 text-primary text-[10px] font-mono uppercase"
              >
                HackerOne
              </Badge>
              Score every report, comment back, optionally auto-close
            </CardTitle>
            <CardDescription className="mt-1">
              Wire H1's{" "}
              <code className="font-mono text-xs text-foreground">
                report-created
              </code>{" "}
              webhook into{" "}
              <code className="font-mono text-xs text-foreground">
                /api/reports/check
              </code>
              , post the composite score as an internal comment, and (opt-in)
              close the AUTO_CLOSE tier with a templated reply. Reference
              shell, Python, and Go scripts inline.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/artifacts/api-server/docs/integrations/hackerone.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-hackerone-recipe"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the HackerOne recipe
              <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-[11px] text-muted-foreground/60 italic mt-2">
              Repo path:{" "}
              <code className="font-mono">
                artifacts/api-server/docs/integrations/hackerone.md
              </code>
            </p>
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-primary/40 text-primary text-[10px] font-mono uppercase"
              >
                Bugcrowd
              </Badge>
              Score every submission, note back, optionally auto-close
            </CardTitle>
            <CardDescription className="mt-1">
              Wire Bugcrowd's{" "}
              <code className="font-mono text-xs text-foreground">
                submission.created
              </code>{" "}
              outbound webhook into{" "}
              <code className="font-mono text-xs text-foreground">
                /api/reports/check
              </code>
              , post the composite score as a team-only note, and (opt-in)
              transition the AUTO_CLOSE tier to{" "}
              <code className="font-mono text-xs text-foreground">
                not_applicable
              </code>{" "}
              with a templated reply. Reference shell + Python scripts inline.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/artifacts/api-server/docs/integrations/bugcrowd.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-bugcrowd-recipe"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the Bugcrowd recipe
              <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-[11px] text-muted-foreground/60 italic mt-2">
              Repo path:{" "}
              <code className="font-mono">
                artifacts/api-server/docs/integrations/bugcrowd.md
              </code>
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Server className="w-5 h-5 text-primary" />
          Self-Hosting
        </h2>
        <p className="text-sm text-muted-foreground">
          Run VulnRap on your own infrastructure. Two reference deployment paths
          — pick the one that matches your stack.
        </p>

        <Card
          className="glass-card rounded-xl"
          data-testid="card-self-host-compose"
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-blue-500 text-blue-500 text-[10px] font-mono uppercase"
              >
                Docker Compose
              </Badge>
              <code className="text-primary font-mono text-xs">
                docker-compose.yml
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Single-host PostgreSQL setup for local development and small
              deployments. Lives at the repo root.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/docker-compose.yml"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-compose-file"
            >
              <FileText className="w-3.5 h-3.5" />
              View docker-compose.yml
              <ExternalLink className="w-3 h-3" />
            </a>
          </CardContent>
        </Card>

        <Card
          className="glass-card rounded-xl"
          data-testid="card-self-host-helm"
        >
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-cyan-500 text-cyan-500 text-[10px] font-mono uppercase"
              >
                Helm
              </Badge>
              <code className="text-primary font-mono text-xs">
                deploy/helm/vulnrap
              </code>
            </CardTitle>
            <CardDescription className="mt-1">
              Kubernetes Helm chart for production deployments. Ships
              Deployment, Service, optional Ingress, ConfigMap, Secret stub,
              ServiceAccount, and an optional HorizontalPodAutoscaler. Lints
              clean with{" "}
              <code className="font-mono text-xs text-foreground">
                helm lint
              </code>
              . Bring your own PostgreSQL.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            <CopyBlock
              language="bash"
              code={`git clone https://github.com/vulnrap/vulnrap.git
cd vulnrap

helm install vulnrap ./deploy/helm/vulnrap \\
  --namespace vulnrap --create-namespace \\
  --set-string secrets.data.DATABASE_URL="postgresql://vulnrap:vulnrap@my-pg:5432/vulnrap" \\
  --set-string secrets.data.OPENAI_API_KEY="sk-..."`}
            />
            <a
              href="https://github.com/vulnrap/vulnrap/blob/main/deploy/helm/vulnrap/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors"
              data-testid="link-helm-chart-readme"
            >
              <FileText className="w-3.5 h-3.5" />
              Read the Helm chart docs
              <ExternalLink className="w-3 h-3" />
            </a>
            <p className="text-[11px] text-muted-foreground/60 italic">
              Repo path: <code className="font-mono">deploy/helm/vulnrap/</code>{" "}
              — verify with{" "}
              <code className="font-mono">helm lint ./deploy/helm/vulnrap</code>
              .
            </p>
          </CardContent>
        </Card>
      </div>

      <Card className="glass-card rounded-xl">
        <CardContent className="p-6 space-y-4">
          <h3 className="font-bold text-sm flex items-center gap-2">
            <Activity className="w-4 h-4 text-primary" />
            Integration Ideas
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-muted-foreground">
            <div className="flex items-start gap-2">
              <span className="text-primary mt-0.5">--</span>
              <span>
                <strong className="text-foreground">CI/CD Gate:</strong> POST
                reports/check in your pipeline to flag AI-generated or duplicate
                submissions before they reach triage.
              </span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-primary mt-0.5">--</span>
              <span>
                <strong className="text-foreground">Triage Dashboard:</strong>{" "}
                Use the verify endpoint to embed validation badges in your
                internal tools.
              </span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-primary mt-0.5">--</span>
              <span>
                <strong className="text-foreground">Slack/Discord Bot:</strong>{" "}
                POST incoming reports and surface slop scores and duplicate
                warnings in your channels.
              </span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-primary mt-0.5">--</span>
              <span>
                <strong className="text-foreground">
                  Vulnerability Platform:
                </strong>{" "}
                Integrate the check endpoint to pre-screen submissions before
                they enter your queue.
              </span>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          Example Scripts
        </h2>
        <p className="text-sm text-muted-foreground">
          Copy-paste scripts you can drop into your workflow:
        </p>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-yellow-500 text-yellow-500 text-[10px] font-mono uppercase"
              >
                Python
              </Badge>
              Batch-check a folder of reports
            </CardTitle>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="python"
              code={`import requests, pathlib, json

reports_dir = pathlib.Path("./reports")
for f in reports_dir.glob("*.txt"):
    r = requests.post("https://vulnrap.com/api/reports/check",
                       files={"file": open(f, "rb")})
    data = r.json()
    score = data.get("slopScore", "?")
    dupes = len(data.get("similarityMatches", []))
    print(f"{f.name}: slop={score}, duplicates={dupes}")`}
            />
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-green-500 text-green-500 text-[10px] font-mono uppercase"
              >
                Bash
              </Badge>
              CI/CD gate — fail pipeline if slop score is too high
            </CardTitle>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="bash"
              code={`#!/bin/bash
# Add to your CI pipeline to reject AI-generated reports
REPORT_FILE="$1"
THRESHOLD=50

RESULT=$(curl -s -X POST https://vulnrap.com/api/reports/check \\
  -F "file=@$REPORT_FILE")

SCORE=$(echo "$RESULT" | jq '.slopScore')
echo "Slop score: $SCORE / 100"

if [ "$SCORE" -gt "$THRESHOLD" ]; then
  echo "FAILED: Report exceeds slop threshold ($THRESHOLD)"
  exit 1
fi
echo "PASSED: Report looks human-written"`}
            />
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Badge
                variant="outline"
                className="border-blue-500 text-blue-500 text-[10px] font-mono uppercase"
              >
                Node.js
              </Badge>
              Slack bot — post analysis results to a channel
            </CardTitle>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="javascript"
              code={`const FormData = require("form-data");
const axios = require("axios");
const fs = require("fs");

async function analyzeAndPost(filePath, slackWebhook) {
  const form = new FormData();
  form.append("file", fs.createReadStream(filePath));

  const { data } = await axios.post(
    "https://vulnrap.com/api/reports/check",
    form, { headers: form.getHeaders() }
  );

  const emoji = data.slopScore < 30 ? ":white_check_mark:"
    : data.slopScore < 70 ? ":warning:" : ":x:";
  const dupes = data.similarityMatches?.length || 0;

  await axios.post(slackWebhook, {
    text: \`\${emoji} *VulnRap Analysis*\\n\`
      + \`Slop Score: \${data.slopScore}/100 (\${data.slopTier})\\n\`
      + \`Similar Reports: \${dupes}\\n\`
      + \`Redacted Items: \${data.redactionSummary?.total || 0}\`
  });
}`}
            />
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Bot className="w-5 h-5 text-primary" />
          MCP Server (for Claude Desktop, Cursor, &amp; agents)
        </h2>
        <p className="text-sm text-muted-foreground">
          A standalone{" "}
          <a
            href="https://modelcontextprotocol.io"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Model Context Protocol
          </a>{" "}
          server exposes the public VulnRap API as MCP tools so any LLM-tool
          ecosystem can call VulnRap from inside an agent chat. The server lives
          in{" "}
          <code className="font-mono text-xs text-foreground">
            lib/mcp-server
          </code>{" "}
          and ships nine tools that map 1:1 to the public REST endpoints —
          reviewer-only endpoints are intentionally not exposed.
        </p>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Tools exposed</CardTitle>
            <CardDescription className="mt-1">
              Each tool wraps a single public endpoint with input validation via{" "}
              <code className="font-mono text-xs text-foreground">
                @workspace/api-zod
              </code>
              .
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
              <div>
                <code className="font-mono text-foreground">score_report</code>{" "}
                → <code className="font-mono">POST /api/reports/check</code>
              </div>
              <div>
                <code className="font-mono text-foreground">lookup_report</code>{" "}
                →{" "}
                <code className="font-mono">
                  GET /api/reports/&#123;id&#125;
                </code>
              </div>
              <div>
                <code className="font-mono text-foreground">query_stats</code> →{" "}
                <code className="font-mono">GET /api/stats</code>
              </div>
              <div>
                <code className="font-mono text-foreground">
                  query_transparency
                </code>{" "}
                →{" "}
                <code className="font-mono">GET /api/public/corpus-stats</code>
              </div>
              <div>
                <code className="font-mono text-foreground">query_gallery</code>{" "}
                → <code className="font-mono">GET /api/reports/feed</code>
              </div>
              <div>
                <code className="font-mono text-foreground">
                  get_drift_summary
                </code>{" "}
                →{" "}
                <code className="font-mono">GET /api/public/drift-summary</code>
              </div>
              <div>
                <code className="font-mono text-foreground">
                  query_signal_metrics
                </code>{" "}
                →{" "}
                <code className="font-mono">
                  GET /api/feedback/holdout-eval
                </code>
              </div>
              <div>
                <code className="font-mono text-foreground">
                  get_cohort_baseline
                </code>{" "}
                → <code className="font-mono">GET /api/cohort/baseline</code>
              </div>
              <div>
                <code className="font-mono text-foreground">test_yourself</code>{" "}
                → <code className="font-mono">GET /api/test/run</code>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Build &amp; run</CardTitle>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="bash"
              code={`pnpm --filter @workspace/mcp-server build
node ./lib/mcp-server/dist/index.js
# Override the API base URL for self-hosted deployments:
VULNRAP_API_BASE_URL=https://my-vulnrap.example pnpm --filter @workspace/mcp-server start`}
            />
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Claude Desktop config</CardTitle>
            <CardDescription className="mt-1">
              Add this block to{" "}
              <code className="font-mono text-xs text-foreground">
                claude_desktop_config.json
              </code>{" "}
              and restart Claude Desktop. The server speaks MCP over stdio — no
              network ports, no auth.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="json"
              code={`{
  "mcpServers": {
    "vulnrap": {
      "command": "node",
      "args": ["/absolute/path/to/lib/mcp-server/dist/index.js"],
      "env": {
        "VULNRAP_API_BASE_URL": "https://vulnrap.com"
      }
    }
  }
}`}
            />
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
          <Plug className="w-5 h-5 text-primary" />
          Webhooks (reviewer-only)
        </h2>
        <p className="text-sm text-muted-foreground">
          Register a destination URL to receive a signed POST whenever a report
          is scored. Registration, listing, and deletion are gated by{" "}
          <code className="font-mono text-xs text-foreground">
            CALIBRATION_TOKEN
          </code>
          ; v1 emits a single event:{" "}
          <code className="font-mono text-xs text-foreground">
            report.scored
          </code>
          . Each delivery includes an HMAC SHA-256 signature header derived from
          the per-webhook signing secret returned exactly once at registration
          time, and is retried with exponential backoff up to 5 attempts before
          the failure counter is incremented.
        </p>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Register a webhook</CardTitle>
            <CardDescription className="mt-1">
              The response includes a{" "}
              <code className="font-mono text-xs text-foreground">secret</code>{" "}
              field — capture it now, only the SHA-256 hash is persisted on the
              server.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="bash"
              code={`curl -X POST https://vulnrap.com/api/webhooks \\
  -H "X-Calibration-Token: $CALIBRATION_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"url": "https://example.com/hooks/vulnrap", "eventTypes": ["report.scored"]}'`}
            />
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">
              Delivery payload &amp; signature
            </CardTitle>
            <CardDescription className="mt-1">
              Each delivery is a JSON POST. Verify the{" "}
              <code className="font-mono text-xs text-foreground">
                X-VulnRap-Signature
              </code>{" "}
              header against the raw request body using your stored secret
              before trusting it.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <CopyBlock
              language="json"
              code={`POST /your-hook
X-VulnRap-Event: report.scored
X-VulnRap-Signature: sha256=<hex>
X-VulnRap-Webhook-Id: 42
X-VulnRap-Delivery-Attempt: 1
Content-Type: application/json

{
  "event": "report.scored",
  "reportId": 1234,
  "slopScore": 78,
  "slopTier": "likely_slop",
  "compositeScore": 81,
  "label": "AI-generated",
  "createdAt": "2026-05-03T17:00:00.000Z"
}`}
            />
            <CopyBlock
              language="javascript"
              code={`import crypto from "node:crypto";

export function verify(rawBody, signatureHeader, secret) {
  const expected = "sha256=" + crypto
    .createHmac("sha256", secret)
    .update(rawBody, "utf8")
    .digest("hex");
  const a = Buffer.from(expected);
  const b = Buffer.from(signatureHeader ?? "");
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}`}
            />
          </CardContent>
        </Card>

        <Card className="glass-card rounded-xl">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">List &amp; delete</CardTitle>
          </CardHeader>
          <CardContent>
            <CopyBlock
              language="bash"
              code={`# List registered webhooks
curl https://vulnrap.com/api/webhooks \\
  -H "X-Calibration-Token: $CALIBRATION_TOKEN"

# Delete one by id
curl -X DELETE https://vulnrap.com/api/webhooks/42 \\
  -H "X-Calibration-Token: $CALIBRATION_TOKEN"`}
            />
          </CardContent>
        </Card>
      </div>

      <div className="text-center text-xs text-muted-foreground/50 pb-4">
        <button
          type="button"
          onClick={() => {
            setSwaggerOpen(true);
            window.scrollTo({ top: 0, behavior: "smooth" });
          }}
          className="hover:text-primary transition-colors"
        >
          Full OpenAPI spec available at /api/docs
        </button>
      </div>
    </div>
  );
}
