{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vulnrap.fullname" . }}
  labels:
    {{- include "vulnrap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
