// AI self-disclosure detector.
//
// Some slop submitters openly admit that their report was generated (or
// substantively drafted) by an AI assistant — the canonical curl HackerOne
// fixture #3295650 ends with "prepared using an AI security assistant to
// ensure comprehensive and reproducible results", and several other
// real-world reports carry similar boilerplate ("Generated with the help
// of an AI assistant", "This report was written by ChatGPT", etc.).
//
// These self-snitching phrases are a narrow class of high-confidence
// signals that the body was machine-authored, distinct from the broader
// curated hand-wavy phrase list (which is reviewer-extensible and used as
// a haircut on the FLAT-family substance score). They warrant their own
// penalty rather than going into the general phrase list because:
//   - the wording is highly specific (no risk of accidentally tripping on
//     normal prose); and
//   - the per-phrase weight from the curated list (6 points, capped at 24
//     across all matches) doesn't move the needle far enough on reports
//     that otherwise score well on legacy substance.
//
// The detector returns a single fixed penalty (no compounding across
// phrases) so a legitimate report that happens to mention drafting help
// from an AI ("I used Claude to draft this summary, full PoC below") gets
// docked exactly once and not enough to crater an otherwise well-evidenced
// submission.
//
// Task #429 — phrase list moved to data/ai-self-disclosure-phrases.json so
// reviewers can append new patterns through
// POST /feedback/calibration/ai-self-disclosure-phrases without a code
// change + redeploy. The bounded-penalty contract is preserved at the
// detector level (one fixed penalty regardless of how many patterns
// match), so extending the list cannot accidentally turn a single phrase
// into compounding damage.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

/**
 * Fixed AVRI Engine 2 penalty applied (once) when one or more AI
 * self-disclosure phrases match the report body. Sized so the curl
 * HackerOne #3295650 fixture lands inside the ≤25 tightening band
 * (Sprint 13B handwavy-phrase + AI-self-disclosure tightening) without
 * cratering a legit, well-evidenced report that happens to admit
 * AI drafting help.
 */
export const AI_SELF_DISCLOSURE_PENALTY = 15;

/**
 * Persisted shape of one phrase entry. `pattern` is a regex source string
 * (verbatim, no leading/trailing slashes); `flags` defaults to "i" when
 * omitted. Audit metadata mirrors the curated hand-wavy phrase list.
 */
export interface AiSelfDisclosurePhrase {
  id: string;
  pattern: string;
  flags?: string;
  /** Reviewer name or email that added this phrase. Undefined for curated defaults. */
  addedBy?: string;
  /** ISO 8601 timestamp the phrase was added. Undefined for curated defaults. */
  addedAt?: string;
  /** Free-text justification supplied by the reviewer at add time. */
  rationale?: string;
}

interface PhrasesFile {
  _meta?: unknown;
  phrases: Array<Record<string, unknown>>;
}

/**
 * Default phrase patterns covering the most common ways slop authors
 * disclose that the report body is AI-generated. Matched
 * case-insensitively against a whitespace-collapsed copy of the report
 * text so multi-line phrasings still match. These defaults are also
 * mirrored verbatim in data/ai-self-disclosure-phrases.json — the JSON
 * file wins when present; this list is the in-memory fallback if the
 * file is missing/empty/corrupt so the detector never silently goes
 * dark.
 */
const DEFAULT_PHRASES: AiSelfDisclosurePhrase[] = [
  // "prepared using an AI security assistant", "prepared with an AI"
  {
    id: "prepared_using_ai",
    pattern:
      "\\bprepared\\s+(?:using|with)\\s+(?:an?\\s+)?(?:ai|artificial intelligence|llm)\\b",
    flags: "i",
  },
  // "generated with the help of an AI assistant", "written by an AI",
  // "produced using ChatGPT", "drafted with Claude", etc.
  {
    id: "generated_with_ai",
    pattern:
      "\\b(?:generated|produced|written|drafted|authored|composed|created|compiled)\\s+(?:by|with|using|via)\\s+(?:the\\s+(?:help|assistance)\\s+of\\s+)?(?:an?\\s+)?(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard|gpt-?\\d?)\\b",
    flags: "i",
  },
  // "with the help of an AI", "with assistance from an AI assistant"
  {
    id: "with_ai_help",
    pattern:
      "\\bwith\\s+(?:the\\s+)?(?:help|assistance)\\s+(?:of|from)\\s+(?:an?\\s+)?(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard)\\b",
    flags: "i",
  },
  // "this report was assisted by an AI", "this report has been generated by ChatGPT"
  {
    id: "this_report_ai",
    pattern:
      "\\bthis\\s+(?:report|analysis|writeup|write[-\\s]?up|submission)\\s+(?:was|is|has\\s+been)\\s+(?:assisted|generated|written|drafted|authored|prepared|created|produced)\\s+(?:by|with|using)\\b[^.]{0,80}\\b(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard|gpt-?\\d?)\\b",
    flags: "i",
  },
  // "AI-generated", "AI generated", "AI-written", "AI-assisted"
  {
    id: "ai_generated_adjective",
    pattern:
      "\\bai[-\\s](?:generated|written|drafted|authored|assisted|produced|composed)\\b",
    flags: "i",
  },
  // "ChatGPT-assisted", "Claude-generated", "Copilot-written"
  {
    id: "named_llm_assisted",
    pattern:
      "\\b(?:chatgpt|claude|copilot|gemini|bard|gpt-?\\d?)[-\\s](?:assisted|generated|written|drafted|authored|produced)\\b",
    flags: "i",
  },
  // "I used Claude to draft this", "we used ChatGPT to write/generate/help with"
  {
    id: "used_llm_to_draft",
    pattern:
      "\\b(?:i|we)\\s+(?:used|asked|leveraged|relied\\s+on)\\s+(?:chatgpt|claude|copilot|gemini|bard|gpt-?\\d?|an?\\s+(?:ai|llm))\\b[^.]{0,80}\\b(?:draft|write|generate|prepare|produce|author|compose|create|summarize|analy[sz]e)\\b",
    flags: "i",
  },
];

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CANDIDATE_PATHS = [
  // dist-relative (after tsc): dist/lib/engines/avri/ -> dist/../../../data
  path.resolve(__dirname, "../../../../data/ai-self-disclosure-phrases.json"),
  // src-relative (vitest / tsx): src/lib/engines/avri/ -> src/../../../data
  path.resolve(__dirname, "../../../../data/ai-self-disclosure-phrases.json"),
  // pkg-root fallback
  path.resolve(process.cwd(), "data/ai-self-disclosure-phrases.json"),
  path.resolve(
    process.cwd(),
    "artifacts/api-server/data/ai-self-disclosure-phrases.json",
  ),
];

const ID_PATTERN = /^[a-z0-9_]{1,64}$/i;
const PATTERN_MAX_LEN = 500;
const FLAGS_PATTERN = /^[gimsuy]{0,7}$/;

interface CompiledPhrase {
  id: string;
  pattern: RegExp;
}

interface CacheState {
  phrases: AiSelfDisclosurePhrase[];
  compiled: CompiledPhrase[];
}

let CACHED: CacheState | null = null;
let RESOLVED_PATH: string | null = null;

function resolvePath(): string {
  if (RESOLVED_PATH) return RESOLVED_PATH;
  // Tests / operators can pin the storage path explicitly via
  // AI_SELF_DISCLOSURE_PHRASES_PATH so tests don't mutate the shipped
  // JSON file. Mirrors HANDWAVY_PHRASES_PATH on the curated list.
  const override = process.env.AI_SELF_DISCLOSURE_PHRASES_PATH;
  if (override && override.trim().length > 0) {
    RESOLVED_PATH = path.resolve(override);
    return RESOLVED_PATH;
  }
  for (const p of CANDIDATE_PATHS) {
    if (existsSync(p)) {
      RESOLVED_PATH = p;
      return p;
    }
  }
  // Fall back to the first candidate so a write can create it on demand.
  RESOLVED_PATH = CANDIDATE_PATHS[0];
  return RESOLVED_PATH;
}

function trimOrUndefined(x: unknown, max: number): string | undefined {
  if (typeof x !== "string") return undefined;
  const v = x.trim();
  if (!v) return undefined;
  return v.length > max ? v.slice(0, max) : v;
}

function isIsoTimestamp(x: unknown): x is string {
  return typeof x === "string" && !Number.isNaN(Date.parse(x));
}

function coercePhrase(entry: unknown): AiSelfDisclosurePhrase | null {
  if (!entry || typeof entry !== "object") return null;
  const obj = entry as Record<string, unknown>;
  if (typeof obj.id !== "string" || !ID_PATTERN.test(obj.id)) return null;
  if (typeof obj.pattern !== "string") return null;
  if (obj.pattern.length === 0 || obj.pattern.length > PATTERN_MAX_LEN)
    return null;
  let flags: string | undefined;
  if (obj.flags !== undefined && obj.flags !== null) {
    if (typeof obj.flags !== "string" || !FLAGS_PATTERN.test(obj.flags))
      return null;
    if (obj.flags.length > 0) flags = obj.flags;
  }
  // Skip entries whose regex does not compile so a single bad row in the
  // JSON file cannot blow up startup.
  try {
    new RegExp(obj.pattern, flags ?? "i");
  } catch {
    return null;
  }
  const out: AiSelfDisclosurePhrase = { id: obj.id, pattern: obj.pattern };
  if (flags !== undefined) out.flags = flags;
  const addedBy = trimOrUndefined(obj.addedBy, 200);
  if (addedBy) out.addedBy = addedBy;
  if (isIsoTimestamp(obj.addedAt)) out.addedAt = obj.addedAt;
  const rationale = trimOrUndefined(obj.rationale, 500);
  if (rationale) out.rationale = rationale;
  return out;
}

function load(): CacheState {
  if (CACHED) return CACHED;
  const p = resolvePath();
  let phrases: AiSelfDisclosurePhrase[] | null = null;
  if (existsSync(p)) {
    try {
      const raw = JSON.parse(readFileSync(p, "utf8")) as PhrasesFile;
      if (Array.isArray(raw.phrases)) {
        phrases = raw.phrases
          .map(coercePhrase)
          .filter((m): m is AiSelfDisclosurePhrase => m !== null);
      }
    } catch {
      // Fall through to defaults so a corrupt JSON file never silently
      // disables the detector.
    }
  }
  if (!phrases || phrases.length === 0) {
    phrases = DEFAULT_PHRASES.map((m) => ({ ...m }));
  }
  // Dedupe by id while preserving order; first occurrence wins.
  const seen = new Set<string>();
  const deduped: AiSelfDisclosurePhrase[] = [];
  for (const ph of phrases) {
    if (!seen.has(ph.id)) {
      seen.add(ph.id);
      deduped.push(ph);
    }
  }
  const compiled: CompiledPhrase[] = deduped.map((ph) => ({
    id: ph.id,
    pattern: new RegExp(ph.pattern, ph.flags ?? "i"),
  }));
  CACHED = { phrases: deduped, compiled };
  return CACHED;
}

function persist(phrases: AiSelfDisclosurePhrase[]): void {
  const p = resolvePath();
  const dir = path.dirname(p);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const body: PhrasesFile = {
    _meta: {
      description:
        "Curated list of AI self-disclosure phrase patterns. Loaded by lib/engines/avri/ai-self-disclosure.ts at startup. Each entry compiles to a RegExp matched (case-insensitively) against a whitespace-collapsed copy of the report text. Reviewers can append new patterns through POST /feedback/calibration/ai-self-disclosure-phrases without a redeploy. The detector enforces a SINGLE fixed penalty (AI_SELF_DISCLOSURE_PENALTY) per report regardless of how many patterns match — the bounded-penalty contract is independent of list size.",
    },
    phrases: phrases as unknown as Array<Record<string, unknown>>,
  };
  writeFileSync(p, JSON.stringify(body, null, 2) + "\n", "utf8");
}

/**
 * Snapshot of the active phrase list (defaults + reviewer additions).
 * Returned copies are independent of the cache so callers can't mutate
 * internal state through the response.
 */
export function getAiSelfDisclosurePhrases(): AiSelfDisclosurePhrase[] {
  return load().phrases.map((p) => ({ ...p }));
}

export interface AddAiSelfDisclosurePhraseOptions {
  reviewer?: string;
  rationale?: string;
  /** Override the timestamp (tests). Defaults to `new Date().toISOString()`. */
  now?: string;
}

export interface AddAiSelfDisclosurePhraseResult {
  added: boolean;
  phrase: AiSelfDisclosurePhrase;
  total: number;
}

/**
 * Append a new phrase pattern to the curated list. Idempotent on `id`:
 * if the id already exists the active marker is returned with
 * `added: false` and the file is left untouched.
 *
 * Validation errors throw with messages prefixed by the offending field
 * name (`id …`, `pattern …`, `flags …`, `rationale …`) so the route can
 * surface them as 400s without leaking unrelated exceptions.
 */
export function addAiSelfDisclosurePhrase(
  rawId: unknown,
  rawPattern: unknown,
  rawFlags: unknown,
  options: AddAiSelfDisclosurePhraseOptions = {},
): AddAiSelfDisclosurePhraseResult {
  if (typeof rawId !== "string" || rawId.trim().length === 0) {
    throw new Error("id must be a non-empty string.");
  }
  const id = rawId.trim();
  if (!ID_PATTERN.test(id)) {
    throw new Error("id must be 1-64 characters of [A-Za-z0-9_].");
  }
  if (typeof rawPattern !== "string" || rawPattern.length === 0) {
    throw new Error("pattern must be a non-empty string.");
  }
  if (rawPattern.length > PATTERN_MAX_LEN) {
    throw new Error(`pattern must be at most ${PATTERN_MAX_LEN} characters.`);
  }
  let flags: string | undefined;
  if (rawFlags !== undefined && rawFlags !== null) {
    if (typeof rawFlags !== "string" || !FLAGS_PATTERN.test(rawFlags)) {
      throw new Error(
        "flags must contain only regex flag characters [gimsuy].",
      );
    }
    if (rawFlags.length > 0) flags = rawFlags;
  }
  try {
    new RegExp(rawPattern, flags ?? "i");
  } catch (e) {
    throw new Error(
      `pattern is not a valid regular expression: ${(e as Error).message}`,
    );
  }
  const reviewer = trimOrUndefined(options.reviewer, 200);
  const rationale = trimOrUndefined(options.rationale, 500);
  if (rationale && rationale.length < 3) {
    throw new Error("rationale must be at least 3 characters when provided.");
  }
  const { phrases: current } = load();
  const existing = current.find((p) => p.id === id);
  if (existing) {
    return { added: false, phrase: { ...existing }, total: current.length };
  }
  const addedAt = isIsoTimestamp(options.now)
    ? options.now
    : new Date().toISOString();
  const phrase: AiSelfDisclosurePhrase = { id, pattern: rawPattern };
  if (flags !== undefined) phrase.flags = flags;
  if (reviewer) phrase.addedBy = reviewer;
  phrase.addedAt = addedAt;
  if (rationale) phrase.rationale = rationale;
  const next = [...current, phrase];
  persist(next);
  // Force the next read to re-parse + recompile the on-disk list so the
  // newly added pattern starts firing on the very next triage.
  CACHED = null;
  return { added: true, phrase: { ...phrase }, total: next.length };
}

export interface AiSelfDisclosureMatch {
  /** Detector id (one of the keys in the active phrase list). */
  id: string;
  /** The exact phrase span that matched, lowercased and length-capped. */
  excerpt: string;
}

export interface AiSelfDisclosureResult {
  /** True iff any phrase pattern matched. */
  detected: boolean;
  /** Per-pattern matches (deduplicated by detector id). */
  matches: AiSelfDisclosureMatch[];
  /** Bounded penalty: AI_SELF_DISCLOSURE_PENALTY when detected, 0 otherwise. */
  penalty: number;
}

/**
 * Detect AI self-disclosure phrases in `text`. Returns a bounded penalty
 * (the same fixed amount whether one or six phrases match) so a legit
 * report that mentions AI drafting help gets docked exactly once.
 */
export function detectAiSelfDisclosure(
  text: string | null | undefined,
): AiSelfDisclosureResult {
  if (!text || typeof text !== "string") {
    return { detected: false, matches: [], penalty: 0 };
  }
  // Collapse whitespace so multi-line prose still matches phrase patterns.
  const normalized = text.replace(/\s+/g, " ");
  const { compiled } = load();
  const matches: AiSelfDisclosureMatch[] = [];
  const seen = new Set<string>();
  for (const { id, pattern } of compiled) {
    if (seen.has(id)) continue;
    const m = normalized.match(pattern);
    if (m && m[0]) {
      seen.add(id);
      matches.push({
        id,
        excerpt: m[0].toLowerCase().slice(0, 160),
      });
    }
  }
  if (matches.length === 0) {
    return { detected: false, matches: [], penalty: 0 };
  }
  return {
    detected: true,
    matches,
    penalty: AI_SELF_DISCLOSURE_PENALTY,
  };
}

/** Test helper: drop the in-memory cache so the next read re-parses the file. */
export function __resetAiSelfDisclosurePhrasesForTests(): void {
  CACHED = null;
  RESOLVED_PATH = null;
}

/** Test helper: rewrite the on-disk file to the curated defaults. */
export function __restoreAiSelfDisclosureDefaultsForTests(): void {
  const defaults = DEFAULT_PHRASES.map((p) => ({ ...p }));
  persist(defaults);
  CACHED = null;
}
