// AI self-disclosure detector.
//
// Some slop submitters openly admit that their report was generated (or
// substantively drafted) by an AI assistant — the canonical curl HackerOne
// fixture #3295650 ends with "prepared using an AI security assistant to
// ensure comprehensive and reproducible results", and several other
// real-world reports carry similar boilerplate ("Generated with the help
// of an AI assistant", "This report was written by ChatGPT", etc.).
//
// These self-snitching phrases are a narrow class of high-confidence
// signals that the body was machine-authored, distinct from the broader
// curated hand-wavy phrase list (which is reviewer-extensible and used as
// a haircut on the FLAT-family substance score). They warrant their own
// penalty rather than going into the general phrase list because:
//   - the wording is highly specific (no risk of accidentally tripping on
//     normal prose), so we don't need the per-phrase reviewer audit trail
//     that the curated list carries; and
//   - the per-phrase weight from the curated list (6 points, capped at 24
//     across all matches) doesn't move the needle far enough on reports
//     that otherwise score well on legacy substance.
//
// The detector returns a single fixed penalty (no compounding across
// phrases) so a legitimate report that happens to mention drafting help
// from an AI ("I used Claude to draft this summary, full PoC below") gets
// docked exactly once and not enough to crater an otherwise well-evidenced
// submission.

/**
 * Fixed AVRI Engine 2 penalty applied (once) when one or more AI
 * self-disclosure phrases match the report body. Sized so the curl
 * HackerOne #3295650 fixture lands inside the ≤25 tightening band
 * (Sprint 13B handwavy-phrase + AI-self-disclosure tightening) without
 * cratering a legit, well-evidenced report that happens to admit
 * AI drafting help.
 */
export const AI_SELF_DISCLOSURE_PENALTY = 15;

/**
 * Phrase patterns covering the most common ways slop authors disclose
 * that the report body is AI-generated. Patterns are matched case
 * -insensitively against a whitespace-collapsed copy of the report
 * text so multi-line phrasings still match. New patterns belong here
 * (they're scoped narrowly enough that there is no curated, reviewer
 * -extensible list); the broader hand-wavy phrase list lives in
 * data/handwavy-phrases.json.
 */
const PHRASE_PATTERNS: ReadonlyArray<{ id: string; pattern: RegExp }> = [
  // "prepared using an AI security assistant", "prepared with an AI"
  {
    id: "prepared_using_ai",
    pattern: /\bprepared\s+(?:using|with)\s+(?:an?\s+)?(?:ai|artificial intelligence|llm)\b/i,
  },
  // "generated with the help of an AI assistant", "written by an AI",
  // "produced using ChatGPT", "drafted with Claude", etc.
  {
    id: "generated_with_ai",
    pattern: /\b(?:generated|produced|written|drafted|authored|composed|created|compiled)\s+(?:by|with|using|via)\s+(?:the\s+(?:help|assistance)\s+of\s+)?(?:an?\s+)?(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard|gpt-?\d?)\b/i,
  },
  // "with the help of an AI", "with assistance from an AI assistant"
  {
    id: "with_ai_help",
    pattern: /\bwith\s+(?:the\s+)?(?:help|assistance)\s+(?:of|from)\s+(?:an?\s+)?(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard)\b/i,
  },
  // "this report was assisted by an AI", "this report has been generated by ChatGPT"
  {
    id: "this_report_ai",
    pattern: /\bthis\s+(?:report|analysis|writeup|write[-\s]?up|submission)\s+(?:was|is|has\s+been)\s+(?:assisted|generated|written|drafted|authored|prepared|created|produced)\s+(?:by|with|using)\b[^.]{0,80}\b(?:ai|artificial intelligence|llm|chatgpt|claude|copilot|gemini|bard|gpt-?\d?)\b/i,
  },
  // "AI-generated", "AI generated", "AI-written", "AI-assisted"
  {
    id: "ai_generated_adjective",
    pattern: /\bai[-\s](?:generated|written|drafted|authored|assisted|produced|composed)\b/i,
  },
  // "ChatGPT-assisted", "Claude-generated", "Copilot-written"
  {
    id: "named_llm_assisted",
    pattern: /\b(?:chatgpt|claude|copilot|gemini|bard|gpt-?\d?)[-\s](?:assisted|generated|written|drafted|authored|produced)\b/i,
  },
  // "I used Claude to draft this", "we used ChatGPT to write/generate/help with"
  {
    id: "used_llm_to_draft",
    pattern: /\b(?:i|we)\s+(?:used|asked|leveraged|relied\s+on)\s+(?:chatgpt|claude|copilot|gemini|bard|gpt-?\d?|an?\s+(?:ai|llm))\b[^.]{0,80}\b(?:draft|write|generate|prepare|produce|author|compose|create|summarize|analy[sz]e)\b/i,
  },
];

export interface AiSelfDisclosureMatch {
  /** Detector id (one of the keys in PHRASE_PATTERNS). */
  id: string;
  /** The exact phrase span that matched, lowercased and length-capped. */
  excerpt: string;
}

export interface AiSelfDisclosureResult {
  /** True iff any phrase pattern matched. */
  detected: boolean;
  /** Per-pattern matches (deduplicated by detector id). */
  matches: AiSelfDisclosureMatch[];
  /** Bounded penalty: AI_SELF_DISCLOSURE_PENALTY when detected, 0 otherwise. */
  penalty: number;
}

/**
 * Detect AI self-disclosure phrases in `text`. Returns a bounded penalty
 * (the same fixed amount whether one or six phrases match) so a legit
 * report that mentions AI drafting help gets docked exactly once.
 */
export function detectAiSelfDisclosure(text: string | null | undefined): AiSelfDisclosureResult {
  if (!text || typeof text !== "string") {
    return { detected: false, matches: [], penalty: 0 };
  }
  // Collapse whitespace so multi-line prose still matches phrase patterns.
  const normalized = text.replace(/\s+/g, " ");
  const matches: AiSelfDisclosureMatch[] = [];
  const seen = new Set<string>();
  for (const { id, pattern } of PHRASE_PATTERNS) {
    if (seen.has(id)) continue;
    const m = normalized.match(pattern);
    if (m && m[0]) {
      seen.add(id);
      matches.push({
        id,
        excerpt: m[0].toLowerCase().slice(0, 160),
      });
    }
  }
  if (matches.length === 0) {
    return { detected: false, matches: [], penalty: 0 };
  }
  return {
    detected: true,
    matches,
    penalty: AI_SELF_DISCLOSURE_PENALTY,
  };
}
